version: '3.4'

services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  #NodeJs services
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Maddie
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  mongo_db: {}

